### PR TITLE
Use textScaler instead of textScale to get rid of deprecation warning

### PR DESCRIPTION
**Pull request by imaNNeo**

### CODE REVIEW

**Comment by cantomris** [comment]
Hi! 

I am getting an error maybe related to this.

`../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/bar_chart/bar_chart_renderer.dart:42:5: Error: Type 'TextScaler' not found.
    TextScaler textScaler,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/bar_chart/bar_chart_renderer.dart:67:3: Error: Type 'TextScaler' not found.
  TextScaler get textScaler => _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/bar_chart/bar_chart_renderer.dart:68:3: Error: Type 'TextScaler' not found.
  TextScaler _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/bar_chart/bar_chart_renderer.dart:70:18: Error: Type 'TextScaler' not found.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/base/base_chart/base_chart_painter.dart:31:9: Error: Type 'TextScaler' not found.
  final TextScaler textScaler;
        ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/line_chart/line_chart_renderer.dart:47:5: Error: Type 'TextScaler' not found.
    TextScaler textScaler,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/line_chart/line_chart_renderer.dart:73:3: Error: Type 'TextScaler' not found.
  TextScaler get textScaler => _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/line_chart/line_chart_renderer.dart:74:3: Error: Type 'TextScaler' not found.
  TextScaler _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/line_chart/line_chart_renderer.dart:75:18: Error: Type 'TextScaler' not found.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/pie_chart/pie_chart_renderer.dart:53:5: Error: Type 'TextScaler' not found.
    TextScaler textScaler,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/pie_chart/pie_chart_renderer.dart:80:3: Error: Type 'TextScaler' not found.
  TextScaler get textScaler => _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/pie_chart/pie_chart_renderer.dart:81:3: Error: Type 'TextScaler' not found.
  TextScaler _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/pie_chart/pie_chart_renderer.dart:83:18: Error: Type 'TextScaler' not found.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/radar_chart/radar_chart_renderer.dart:46:5: Error: Type 'TextScaler' not found.
    TextScaler textScaler,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/radar_chart/radar_chart_renderer.dart:71:3: Error: Type 'TextScaler' not found.
  TextScaler get textScaler => _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/radar_chart/radar_chart_renderer.dart:72:3: Error: Type 'TextScaler' not found.
  TextScaler _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/radar_chart/radar_chart_renderer.dart:74:18: Error: Type 'TextScaler' not found.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/scatter_chart/scatter_chart_renderer.dart:50:5: Error: Type 'TextScaler' not found.
    TextScaler textScaler,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/scatter_chart/scatter_chart_renderer.dart:75:3: Error: Type 'TextScaler' not found.
  TextScaler get textScaler => _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/scatter_chart/scatter_chart_renderer.dart:76:3: Error: Type 'TextScaler' not found.
  TextScaler _textScaler;
  ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/scatter_chart/scatter_chart_renderer.dart:78:18: Error: Type 'TextScaler' not found.
  set textScaler(TextScaler value) {
                 ^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/bar_chart/bar_chart_renderer.dart:22:32: Error: The getter 'textScaler' isn't defined for the class 'MediaQueryData'.
 - 'MediaQueryData' is from 'package:flutter/src/widgets/media_query.dart' ('../../FlutterDev/flutter/packages/flutter/lib/src/widgets/media_query.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
        MediaQuery.of(context).textScaler,
                               ^^^^^^^^^^
`

Please let me know if you need more information about this. Thanks.

**Comment by imaNNeo** [comment]
What's your flutter version? Are you using the latest version?

**Comment by dananee** [comment]
Hey, I have the same issue any update on how to fix it?

**Comment by dananee** [comment]
> What's your flutter version? Are you using the latest version?

I work on old project with flutter version 3.13.9

**Comment by cantomris** [comment]
Mine is an old version as well 3.10.6.

**Comment by imaNNeo** [comment]
Okay so don't upgrade the fl_chart version before you upgrade the Flutter version.
because the new fl_chart version is only compatible with the new Flutter version because of this breaking change introduced by Flutter

**Comment by cantomris** [comment]
Oh I see. Thanks.

**Pull request merged**
