### PR TITLE
BUGFIX Fix bargraph overflow

### PR DESCRIPTION
**Pull request by bobatsar**
- If bargraphs overflow (more bars than the available space)  with `BarChartAlignment.start`, `BarChartAlignment.center` or `BarChartAlignment.end`, use `BarChartAlignment.spaceEvenly` to shrink all bars to the available space
- Update documentation for `BarChartData.groupsSpace`

If the automatic approach to shrink all bars is not desired, another option would be to add other alignments e.g. `BarChartAlignment.startShrink` or another parameter to enable `shrink on overflow`.

### CODE REVIEW

**Comment by imaNNeo** [comment]
Hi, please read the [Contributing guideline](https://github.com/imaNNeo/fl_chart#contributing) carefully
* You need to update the unit-tests (run `make sure` to make sure that everything is working well)
* You need to update the Changelog.md

**Comment by bobatsar** [comment]
@imaNNeo I just added a widget test (with golden files). I didn't find another way to check if the bars are drawn outside of the diagram. I can't check for the bars with a finder due to the fact that they are rendered on the canvas.
If you know a better approach, please tell me and I will fix it.

**Comment by imaNNeo** [comment]
Nice, I need to learn more about the golden tests.
Thanks for your contribution!

**Comment by bobatsar** [comment]
Hey @imaNNeo , thanks for merging.

For golden tests I can also recommend the following package.
I use it quite extensively e.g. for testing different device sizes.

https://pub.dev/packages/golden_toolkit

**Comment by k0psutin** [comment]
Golden tests are a good way to see if something has changed drastically. It's just that golden tests give different results on different OS - I think there should be some fault tolerance (0.2%) for the tests. At least for me, because I use Windows, I get failed tests on `master` because 0.15 - 0.2% differences.

```
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +41: D:/Code/fl_chart/test/chart/bar_chart/bar_chart_alignment_widget_test.dart: Barchart alignment overflow test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "golden/BarChartAlignment.start_20.0.png": Pixel test failed, 0.20% diff detected.
Failure feedback can be found at /D:/Code/fl_chart/test/chart/bar_chart/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:101:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

**Comment by k0psutin** [comment]
See https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter#creating-a-new-golden-file-test

Quote from link:

Golden tests may be executed locally on Linux, MacOS, and Windows platforms. All reference images can be found at [Flutter Gold baselines](https://flutter-gold.skia.org/list?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&limit=50&master=false&match=name&metric=combined&neg=false&new_clstore=true&offset=0&pos=true&query=source_type%3Dflutter&sort=desc&unt=true). Some tests may have multiple golden masters for a given test, to account for rendering differences across platforms. The parameter set for each image is listed in each image digest to differentiate renderings.

**Comment by imaNNeo** [comment]
@k0psutin You're right, I get about 93% diff on my machine 😆
image

**Comment by bobatsar** [comment]
@imaNNeo sorry if the golden test make issues.

@k0psutin 
There is a way to add a fault tolerance.

https://stackoverflow.com/a/73048760/3607358 or 
https://medium.com/mobilepeople/how-to-add-difference-tolerance-to-golden-tests-on-flutter-2d899c8baad2

I use this also for my tests in another project.
I could add this in the next days if it is wanted.

@imaNNeo but 93% diff is another level. There must be something completely off on your side. Did you check the failure images?

**Comment by imaNNeo** [comment]
No worries @bobatsar 

Yes, I was in the latest version (3.16.0). 
And about the OS, I think one OS might be enough with a tolerance.

**Pull request merged**
