### PR TITLE
AnnotationRange coordinates (Issue: #969)

### PR DESCRIPTION
**Pull request by Dnathan33**
Addresses and resolves issue noted in issue #969

### CODE REVIEW

**Comment by Dnathan33** [comment]
cc @imaNNeoFighT

**Comment by imaNNeoFighT** [comment]
Please answer [this comment](https://github.com/imaNNeoFighT/fl_chart/issues/969#issuecomment-1094118601) first.

**Comment by Dnathan33** [comment]
@imaNNeoFighT Addressed your comment

**Comment by imaNNeoFighT** [comment]
What if we handle it in a built-in way?

**Comment by imaNNeoFighT** [comment]
Implementing a generic way to convert the chart's coordinate system to Flutter's coordinate is better.
For example, you have a `_chartController` reference, then you call `_chartController.converToPixels(x: 10, y: 3)` and it returns something equalivent to the Flutter coordinate system.

**Comment by imaNNeoFighT** [comment]
Because something related asked here: #801

**Comment by Dnathan33** [comment]
> Implementing a generic way to convert the chart's coordinate system to Flutter's coordinate is better.
> For example, you have a `_chartController` reference, then you call `_chartController.converToPixels(x: 10, y: 3)` and it returns something equalivent to the Flutter coordinate system.

Screen Shot 2022-10-26 at 11 26 26 AM

@imaNNeoFighT  If you can see from the attached image above (last chart) this PR only adds logic to get the coordinates of the starting and ending point of annotations. It does not generate coordinates based on user interaction and there is no need to convert the chart's coordinate system to Flutter's coordinate.

**Comment by Dnathan33** [comment]
@imaNNeoFighT Following up on this.

**Comment by imaNNeo** [comment]
So we have restructured the underlying drawing logic. Now titles are widgets and I think we can implement this feature using widgets and allow people to put anything they want. Please check the axis_chart_scaffold_widget.dart

https://github.com/imaNNeo/fl_chart/blob/e2ed862bbfaa0931a6fca1b0141d3feb240c37c1/lib/src/chart/base/axis_chart/axis_chart_scaffold_widget.dart#L11-L17

**Pull request closed without merging**
