### PR TITLE
New property PieChartData.titleSunbeamLayout to rotate the titles of each section of the chart

### PR DESCRIPTION
**Pull request by herna**
The idea is taken from the following library, property `labelSunbeamLayout`: https://krispo.github.io/angular-nvd3/#/pieChart

You can set the property `titleSunbeamLayout` in `PieChartData` to rotate the titles.

By default is set to `false` to not modify any existing code:

By if you set it `true` it'll look like this:

This is specially useful for large sets of data where titles can easily overlap.

### CODE REVIEW

**Comment by imaNNeo** [comment]
It is a nice feature.
Thank you so much
btw, there is an issue, I think the pointed value should be upside down.

Screenshot 2024-02-28 at 21 49 51

**Comment by imaNNeo** [comment]
Also, you need to write some unit-tests

**Comment by herna** [comment]
I made a typo on the upper limit to rotate the title, well-trained eye 😃 

I also wrote some unit tests and made some other minor adjustments, let's see now.

**Comment by imaNNeo** [comment]
Thank you so much!
It's approved and ready to be merged.
Just a minor thing to do, can you please update the [pie_chart.md](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/pie_chart.md#piechartdata) documentation to add the new property?

**Comment by imaNNeo** [comment]
Thanks for your contribution!

**Pull request merged**
