### PR TITLE
add `isEnableCache` option, fix memory lake

### PR DESCRIPTION
**Pull request by wenjiasen**
add `isEnableCache` option, fix memory lake on a dynamic line chart #1106

### CODE REVIEW

**Review by wenjiasen — COMMENTED** [review]
When the data of the chart is changing with time, `_cachedResults` in `calculateMaxAxisValues` will not be able to free the data of the old time, which will inevitably lead to a memory leak, and in the absence of a better solution, at least provide a switch to avoid an OOM.

**Comment by imaNNeo** [comment]
It is a trade-off between memory usage and CPU usage.
At this time we decided to sacrifice memory which leads to memory leaks.
If we put a flag, we sacrifice the CPU (a duplicate calculation happens every time). So nothing fixed.
Actually, I am considering deleting the cache system and dealing with the root issue (recalculation issue). There might be some ways to do that.
For example, we can make all of the minX, maxX, minY, and maxY nullable and calculate them in the chart widgets, so we can have a manageable memory and it removes when widget disposes (no more static variables)

What do you think?

**Comment by wenjiasen** [comment]
Thank you for your response. I think the priority of avoiding OOM would be higher than CPU usage, and it might be necessary to provide a way to prevent OOM in dynamic lists before the cache system is fully optimized.

Unexpected crashes may bring unknown risks in scenarios where long-term operation is required, and could cause unnecessary trouble in production environments.

**Comment by DionaSoft** [comment]
I also experience this problem wit flutter_bloc
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<GraphBloc, GraphState>(
      builder: (context, state) {
        return LineChart(
                            LineChartData(
                              lineBarsData: [
                                LineChartBarData(
                                  spots: state.spots,   // List<FlSpot> spots;
                                  ......
                                ),
                              ],
                              .......
                            ),
                            .......
                          ),
      }
}
 It causes heavy memory leaks.
 version 0.61.0

**Pull request closed without merging**
